### ISSUE TITLE
Clarification of Deploy Process

### ISSUE THREAD

**Issue by bearrito** [dbnicholson/deb-ostree-builder#5]
I posted a question similar to this on the ostree-dev list but I'm having more luck using this library, so I figured I would post it here.

### My setup

**Two vagrant machines**
ostree-dev - Performing ostree commit builds here and hosting the repo via http
ostree-test - I'm attempting to use this as my deploy target.

### My questions

I'm largely able to get to here - [Deploy](https://github.com/dbnicholson/deb-ostree-builder/blob/simple-builder/create-deployment#L28) on my ostree-test system

Lines 33-55 are novel to me. I don't believe I saw something similar in the primary documentation. 

Where my mental model is breaking down is the statement "# Now $EIB_OSTREE_SYSROOT is ready to be written to some disk" from [HERE](https://github.com/dbnicholson/deb-ostree-builder/blob/simple-builder/create-deployment#L57)

My assumption was that running `ostree deploy` turns a target system into a running ostree system. It seems like that is not the case. That's also echoed by the statement in this issue https://github.com/dbnicholson/deb-ostree-builder/issues/4#issuecomment-754298065. Quoting `device is a directory where you'll build the contents to actually flash to the device:`

So is the intent of the deploy process to create another root fileystem that can then be deployed by whatever means (presumably image creation)?

**Comment by dbnicholson** [comment]
I can clarify here, but let me follow up on your mailing list post. I meant to do that yesterday and got busy.

**Comment by bearrito** [comment]
Sorry for being pushy and impatient. I'm really excited to get this working though. It's going to be a big benefit to our company.

I'll add one thing here: 

I'm running into
```
vagrant@ostree-test-1:/var/tmp/ostree-deploy.33Lqxd5AqI$ sudo ostree admin --sysroot="${EIB_OSTREE_SYSROOT}" deploy --os=${EIB_OSTREE_OS} "${kargs[@]}" ${EIB_OSTREE_OS}:${EIB_OSTREE_BRANCH_DEPLOY}
Relabeling /var (no stamp file 'var/.ostree-selabeled' found)
error: Bootloader write config: /usr/sbin/grub-mkconfig: Child process exited with code 1
 ```
